# Generated by Django 3.2 on 2021-05-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='thumbnail',
            field=models.ImageField(upload_to='album/kabir/photo/'),
        ),
    ]
